Sukh submission fe
Tonyhanna9/41129SIS pull request #3
Opened 2022-09-14 08:02 UTC by sukhpreetp

Current UI (button needs to connect with home page): 
![Image 15133](https://user-images.githubusercontent.com/45621432/190096473-b237eedf-7a02-4de8-86ba-c08604d7fb50.jpeg)

2022-09-14 08:29 UTC, TheerthaS requested changes

2022-09-14 08:29 UTC, TheerthaS commented on src/screens/auth/SubmissionConfirm.js
> +            ><Entypo name="dot-single" size={20} color="black" />Go inside but stay alert</Text>
the dot points look a little off in the screenshot. Maybe you could see FlatList? https://reactnative.dev/docs/flatlist

2022-09-14 08:29 UTC, TheerthaS commented on src/navigation/AppNavigator.js
> -import Login from "../screens/auth/Login";
was there a reason you deleted this?

2022-09-14 11:45 UTC, TheerthaS commented on src/navigation/AppNavigator.js
> -import Login from "../screens/auth/Login";
Also maybe we should move this screen out of /auth since it's not really auth stuff?

2022-09-19 12:38 UTC, sukhpreetp commented on src/navigation/AppNavigator.js
> -import Login from "../screens/auth/Login";
That was just to view the UI. I have fixed this

2022-09-19 12:39 UTC, sukhpreetp commented on src/screens/auth/SubmissionConfirm.js
> +            ><Entypo name="dot-single" size={20} color="black" />Go inside but stay alert</Text>
I have tried implementing that but to me it still looks the same (maybe I just can't see) but I think for now lets keep this and if we have time we can change it

2022-09-21 01:18 UTC, TheerthaS approved these changes

2022-09-21 01:18 UTC, TheerthaS commented on src/screens/auth/SubmissionConfirm.js
> +            ><Entypo name="dot-single" size={20} color="black" />Go inside but stay alert</Text>
sounds good!

2022-09-27 11:17 UTC, merged